config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bids

  resources :sales

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
	#un Bid pertenece a un sale
	belongs_to :sale
	#un Bid pertenece a un user
	belongs_to :user
end

app/models/sale.rb
class Sale < ActiveRecord::Base

	#un sale tiene muchos comentarios
	has_many :bids
	#un sale le pertenece a un user
	belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :sales
  has_many :bids

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  #metodo para no destruir sin estar logeado


  def create
    #asignamos al objeto pin un registro que corresponde a pin_id que estamos evaluando, en la url
  @sale =Sale.find(params[:sale_id])
  #
  @bid = Bid.new(bid_params)

  #al comentario le asocio un pin especifico, el cargado en memoria, a esto le asigno el objeto @pin
  @bid.sale = @sale

  #guardo el objeto pin llamando a su metodo .save
  @bid.save

  #finbalmente se redirige al al pin con el comentario /pìn/1
  redirect_to @sale

  end

  # GET /bids
  # GET /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
  end

  # GET /bids/new
  def new

    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1
  # PATCH/PUT /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bid_params
      params.require(:bid).permit(:comment, :price, :user_id, :sale_id)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @bid = Bid.new sale: @sale
    @bids = @sale.bids
  end


  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:name, :photo, :description, :start_price, :user_id, :push_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


def index

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bids/_form.html.erb
<%= form_for(@bid) do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% @bid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :sale_id %><br>
    <%= f.number_field :sale_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bids</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>Price</th>
      <th>User</th>
      <th>Sale</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.comment %></td>
        <td><%= bid.price %></td>
        <td><%= bid.user_id %></td>
        <td><%= bid.sale_id %></td>
        <td><%= link_to 'Show', bid %></td>
        <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
        <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<h1>New Bid</h1>

<%= render 'form' %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @bid.comment %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bid.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @bid.user_id %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @bid.sale_id %>
</p>

<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Remate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :start_price %><br>
    <%= f.number_field :start_price %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :bid_id %><br>
    <%= f.number_field :bid_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Photo</th>
      <th>Description</th>
      <th>Start price</th>
      <th>User</th>
      <th>bid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.name %></td>
        <td><%= sale.photo %></td>
        <td><%= sale.description %></td>
        <td><%= sale.start_price %></td>
        <td><%= sale.user_id %></td>
        <td><%= sale.bid_id %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sale.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @sale.photo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sale.description %>
</p>

<p>
  <strong>Start price:</strong>
  <%= @sale.start_price %>
</p>


<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>



<h2>Oferta para este remate </h2>
<%= form_for(@sale.bids.new) do |f| %>
 <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
 </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
 </div>
<% end %>


<h2>Últimas ofertas</h2>

<% @bids.each do |c| %>
<%= c.comment %>
<% end %>

app/views/welcome/index.html.erb
<html>
	


<h1><%= link_to 'Ingrese un nuevo remate', new_sale_path %></h1>





</html>